/*
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.ui;

import com.aestheticintegration.atto.dsl.ui.internal.DslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ItlDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DslActivator.getInstance().getInjector(DslActivator.COM_AESTHETICINTEGRATION_ATTO_ITLDSL);
	}
	
}
