/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto;

import com.aestheticintegration.atto.AbstractItlDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ItlDslRuntimeModule extends AbstractItlDslRuntimeModule {
}
