/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto;

import com.aestheticintegration.atto.ItlDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ItlDslStandaloneSetup extends ItlDslStandaloneSetupGenerated {
  public static void doSetup() {
    new ItlDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
