/*
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.ui.tests;

import com.aestheticintegration.atto.dsl.ui.internal.DslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ItlDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("com.aestheticintegration.atto.ItlDsl");
	}

}
