/*
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractItlDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.aestheticintegration.atto.itlDsl.ItlDslPackage.eINSTANCE);
		return result;
	}
	
}
