/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl.impl;

import com.aestheticintegration.atto.itlDsl.DataType;
import com.aestheticintegration.atto.itlDsl.DefDataType;
import com.aestheticintegration.atto.itlDsl.ItlDslPackage;

import java.lang.String;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getBoolean <em>Boolean</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getBooleanObj <em>Boolean Obj</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getShort <em>Short</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getShortObj <em>Short Obj</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getInt <em>Int</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getIntObj <em>Int Obj</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getLong <em>Long</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getLongObj <em>Long Obj</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getFloat <em>Float</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getFloatObj <em>Float Obj</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getDouble <em>Double</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getDoubleObj <em>Double Obj</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getString <em>String</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.impl.DataTypeImpl#getDefDataType <em>Def Data Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DataTypeImpl extends MinimalEObjectImpl.Container implements DataType
{
  /**
   * The default value of the '{@link #getBoolean() <em>Boolean</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBoolean()
   * @generated
   * @ordered
   */
  protected static final String BOOLEAN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBoolean() <em>Boolean</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBoolean()
   * @generated
   * @ordered
   */
  protected String boolean_ = BOOLEAN_EDEFAULT;

  /**
   * The default value of the '{@link #getBooleanObj() <em>Boolean Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBooleanObj()
   * @generated
   * @ordered
   */
  protected static final String BOOLEAN_OBJ_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBooleanObj() <em>Boolean Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBooleanObj()
   * @generated
   * @ordered
   */
  protected String booleanObj = BOOLEAN_OBJ_EDEFAULT;

  /**
   * The default value of the '{@link #getShort() <em>Short</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShort()
   * @generated
   * @ordered
   */
  protected static final String SHORT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getShort() <em>Short</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShort()
   * @generated
   * @ordered
   */
  protected String short_ = SHORT_EDEFAULT;

  /**
   * The default value of the '{@link #getShortObj() <em>Short Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortObj()
   * @generated
   * @ordered
   */
  protected static final String SHORT_OBJ_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getShortObj() <em>Short Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortObj()
   * @generated
   * @ordered
   */
  protected String shortObj = SHORT_OBJ_EDEFAULT;

  /**
   * The default value of the '{@link #getInt() <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInt()
   * @generated
   * @ordered
   */
  protected static final String INT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInt() <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInt()
   * @generated
   * @ordered
   */
  protected String int_ = INT_EDEFAULT;

  /**
   * The default value of the '{@link #getIntObj() <em>Int Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntObj()
   * @generated
   * @ordered
   */
  protected static final String INT_OBJ_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIntObj() <em>Int Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntObj()
   * @generated
   * @ordered
   */
  protected String intObj = INT_OBJ_EDEFAULT;

  /**
   * The default value of the '{@link #getLong() <em>Long</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLong()
   * @generated
   * @ordered
   */
  protected static final String LONG_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLong() <em>Long</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLong()
   * @generated
   * @ordered
   */
  protected String long_ = LONG_EDEFAULT;

  /**
   * The default value of the '{@link #getLongObj() <em>Long Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLongObj()
   * @generated
   * @ordered
   */
  protected static final String LONG_OBJ_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLongObj() <em>Long Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLongObj()
   * @generated
   * @ordered
   */
  protected String longObj = LONG_OBJ_EDEFAULT;

  /**
   * The default value of the '{@link #getFloat() <em>Float</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFloat()
   * @generated
   * @ordered
   */
  protected static final String FLOAT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFloat() <em>Float</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFloat()
   * @generated
   * @ordered
   */
  protected String float_ = FLOAT_EDEFAULT;

  /**
   * The default value of the '{@link #getFloatObj() <em>Float Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFloatObj()
   * @generated
   * @ordered
   */
  protected static final String FLOAT_OBJ_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFloatObj() <em>Float Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFloatObj()
   * @generated
   * @ordered
   */
  protected String floatObj = FLOAT_OBJ_EDEFAULT;

  /**
   * The default value of the '{@link #getDouble() <em>Double</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDouble()
   * @generated
   * @ordered
   */
  protected static final String DOUBLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDouble() <em>Double</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDouble()
   * @generated
   * @ordered
   */
  protected String double_ = DOUBLE_EDEFAULT;

  /**
   * The default value of the '{@link #getDoubleObj() <em>Double Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDoubleObj()
   * @generated
   * @ordered
   */
  protected static final String DOUBLE_OBJ_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDoubleObj() <em>Double Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDoubleObj()
   * @generated
   * @ordered
   */
  protected String doubleObj = DOUBLE_OBJ_EDEFAULT;

  /**
   * The default value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected static final String STRING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected String string = STRING_EDEFAULT;

  /**
   * The cached value of the '{@link #getDefDataType() <em>Def Data Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefDataType()
   * @generated
   * @ordered
   */
  protected DefDataType defDataType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ItlDslPackage.Literals.DATA_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getBoolean()
  {
    return boolean_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBoolean(String newBoolean)
  {
    String oldBoolean = boolean_;
    boolean_ = newBoolean;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__BOOLEAN, oldBoolean, boolean_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getBooleanObj()
  {
    return booleanObj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBooleanObj(String newBooleanObj)
  {
    String oldBooleanObj = booleanObj;
    booleanObj = newBooleanObj;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__BOOLEAN_OBJ, oldBooleanObj, booleanObj));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getShort()
  {
    return short_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setShort(String newShort)
  {
    String oldShort = short_;
    short_ = newShort;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__SHORT, oldShort, short_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getShortObj()
  {
    return shortObj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setShortObj(String newShortObj)
  {
    String oldShortObj = shortObj;
    shortObj = newShortObj;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__SHORT_OBJ, oldShortObj, shortObj));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getInt()
  {
    return int_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInt(String newInt)
  {
    String oldInt = int_;
    int_ = newInt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__INT, oldInt, int_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIntObj()
  {
    return intObj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIntObj(String newIntObj)
  {
    String oldIntObj = intObj;
    intObj = newIntObj;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__INT_OBJ, oldIntObj, intObj));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLong()
  {
    return long_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLong(String newLong)
  {
    String oldLong = long_;
    long_ = newLong;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__LONG, oldLong, long_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLongObj()
  {
    return longObj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLongObj(String newLongObj)
  {
    String oldLongObj = longObj;
    longObj = newLongObj;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__LONG_OBJ, oldLongObj, longObj));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFloat()
  {
    return float_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFloat(String newFloat)
  {
    String oldFloat = float_;
    float_ = newFloat;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__FLOAT, oldFloat, float_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFloatObj()
  {
    return floatObj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFloatObj(String newFloatObj)
  {
    String oldFloatObj = floatObj;
    floatObj = newFloatObj;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__FLOAT_OBJ, oldFloatObj, floatObj));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDouble()
  {
    return double_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDouble(String newDouble)
  {
    String oldDouble = double_;
    double_ = newDouble;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__DOUBLE, oldDouble, double_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDoubleObj()
  {
    return doubleObj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDoubleObj(String newDoubleObj)
  {
    String oldDoubleObj = doubleObj;
    doubleObj = newDoubleObj;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__DOUBLE_OBJ, oldDoubleObj, doubleObj));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getString()
  {
    return string;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setString(String newString)
  {
    String oldString = string;
    string = newString;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__STRING, oldString, string));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DefDataType getDefDataType()
  {
    if (defDataType != null && defDataType.eIsProxy())
    {
      InternalEObject oldDefDataType = (InternalEObject)defDataType;
      defDataType = (DefDataType)eResolveProxy(oldDefDataType);
      if (defDataType != oldDefDataType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ItlDslPackage.DATA_TYPE__DEF_DATA_TYPE, oldDefDataType, defDataType));
      }
    }
    return defDataType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DefDataType basicGetDefDataType()
  {
    return defDataType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDefDataType(DefDataType newDefDataType)
  {
    DefDataType oldDefDataType = defDataType;
    defDataType = newDefDataType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ItlDslPackage.DATA_TYPE__DEF_DATA_TYPE, oldDefDataType, defDataType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ItlDslPackage.DATA_TYPE__BOOLEAN:
        return getBoolean();
      case ItlDslPackage.DATA_TYPE__BOOLEAN_OBJ:
        return getBooleanObj();
      case ItlDslPackage.DATA_TYPE__SHORT:
        return getShort();
      case ItlDslPackage.DATA_TYPE__SHORT_OBJ:
        return getShortObj();
      case ItlDslPackage.DATA_TYPE__INT:
        return getInt();
      case ItlDslPackage.DATA_TYPE__INT_OBJ:
        return getIntObj();
      case ItlDslPackage.DATA_TYPE__LONG:
        return getLong();
      case ItlDslPackage.DATA_TYPE__LONG_OBJ:
        return getLongObj();
      case ItlDslPackage.DATA_TYPE__FLOAT:
        return getFloat();
      case ItlDslPackage.DATA_TYPE__FLOAT_OBJ:
        return getFloatObj();
      case ItlDslPackage.DATA_TYPE__DOUBLE:
        return getDouble();
      case ItlDslPackage.DATA_TYPE__DOUBLE_OBJ:
        return getDoubleObj();
      case ItlDslPackage.DATA_TYPE__STRING:
        return getString();
      case ItlDslPackage.DATA_TYPE__DEF_DATA_TYPE:
        if (resolve) return getDefDataType();
        return basicGetDefDataType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ItlDslPackage.DATA_TYPE__BOOLEAN:
        setBoolean((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__BOOLEAN_OBJ:
        setBooleanObj((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__SHORT:
        setShort((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__SHORT_OBJ:
        setShortObj((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__INT:
        setInt((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__INT_OBJ:
        setIntObj((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__LONG:
        setLong((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__LONG_OBJ:
        setLongObj((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__FLOAT:
        setFloat((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__FLOAT_OBJ:
        setFloatObj((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__DOUBLE:
        setDouble((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__DOUBLE_OBJ:
        setDoubleObj((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__STRING:
        setString((String)newValue);
        return;
      case ItlDslPackage.DATA_TYPE__DEF_DATA_TYPE:
        setDefDataType((DefDataType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ItlDslPackage.DATA_TYPE__BOOLEAN:
        setBoolean(BOOLEAN_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__BOOLEAN_OBJ:
        setBooleanObj(BOOLEAN_OBJ_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__SHORT:
        setShort(SHORT_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__SHORT_OBJ:
        setShortObj(SHORT_OBJ_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__INT:
        setInt(INT_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__INT_OBJ:
        setIntObj(INT_OBJ_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__LONG:
        setLong(LONG_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__LONG_OBJ:
        setLongObj(LONG_OBJ_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__FLOAT:
        setFloat(FLOAT_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__FLOAT_OBJ:
        setFloatObj(FLOAT_OBJ_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__DOUBLE:
        setDouble(DOUBLE_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__DOUBLE_OBJ:
        setDoubleObj(DOUBLE_OBJ_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__STRING:
        setString(STRING_EDEFAULT);
        return;
      case ItlDslPackage.DATA_TYPE__DEF_DATA_TYPE:
        setDefDataType((DefDataType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ItlDslPackage.DATA_TYPE__BOOLEAN:
        return BOOLEAN_EDEFAULT == null ? boolean_ != null : !BOOLEAN_EDEFAULT.equals(boolean_);
      case ItlDslPackage.DATA_TYPE__BOOLEAN_OBJ:
        return BOOLEAN_OBJ_EDEFAULT == null ? booleanObj != null : !BOOLEAN_OBJ_EDEFAULT.equals(booleanObj);
      case ItlDslPackage.DATA_TYPE__SHORT:
        return SHORT_EDEFAULT == null ? short_ != null : !SHORT_EDEFAULT.equals(short_);
      case ItlDslPackage.DATA_TYPE__SHORT_OBJ:
        return SHORT_OBJ_EDEFAULT == null ? shortObj != null : !SHORT_OBJ_EDEFAULT.equals(shortObj);
      case ItlDslPackage.DATA_TYPE__INT:
        return INT_EDEFAULT == null ? int_ != null : !INT_EDEFAULT.equals(int_);
      case ItlDslPackage.DATA_TYPE__INT_OBJ:
        return INT_OBJ_EDEFAULT == null ? intObj != null : !INT_OBJ_EDEFAULT.equals(intObj);
      case ItlDslPackage.DATA_TYPE__LONG:
        return LONG_EDEFAULT == null ? long_ != null : !LONG_EDEFAULT.equals(long_);
      case ItlDslPackage.DATA_TYPE__LONG_OBJ:
        return LONG_OBJ_EDEFAULT == null ? longObj != null : !LONG_OBJ_EDEFAULT.equals(longObj);
      case ItlDslPackage.DATA_TYPE__FLOAT:
        return FLOAT_EDEFAULT == null ? float_ != null : !FLOAT_EDEFAULT.equals(float_);
      case ItlDslPackage.DATA_TYPE__FLOAT_OBJ:
        return FLOAT_OBJ_EDEFAULT == null ? floatObj != null : !FLOAT_OBJ_EDEFAULT.equals(floatObj);
      case ItlDslPackage.DATA_TYPE__DOUBLE:
        return DOUBLE_EDEFAULT == null ? double_ != null : !DOUBLE_EDEFAULT.equals(double_);
      case ItlDslPackage.DATA_TYPE__DOUBLE_OBJ:
        return DOUBLE_OBJ_EDEFAULT == null ? doubleObj != null : !DOUBLE_OBJ_EDEFAULT.equals(doubleObj);
      case ItlDslPackage.DATA_TYPE__STRING:
        return STRING_EDEFAULT == null ? string != null : !STRING_EDEFAULT.equals(string);
      case ItlDslPackage.DATA_TYPE__DEF_DATA_TYPE:
        return defDataType != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (boolean: ");
    result.append(boolean_);
    result.append(", booleanObj: ");
    result.append(booleanObj);
    result.append(", short: ");
    result.append(short_);
    result.append(", shortObj: ");
    result.append(shortObj);
    result.append(", int: ");
    result.append(int_);
    result.append(", intObj: ");
    result.append(intObj);
    result.append(", long: ");
    result.append(long_);
    result.append(", longObj: ");
    result.append(longObj);
    result.append(", float: ");
    result.append(float_);
    result.append(", floatObj: ");
    result.append(floatObj);
    result.append(", double: ");
    result.append(double_);
    result.append(", doubleObj: ");
    result.append(doubleObj);
    result.append(", string: ");
    result.append(string);
    result.append(')');
    return result.toString();
  }

} //DataTypeImpl
