/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.ide;

import com.aestheticintegration.atto.ide.AbstractItlDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ItlDslIdeModule extends AbstractItlDslIdeModule {
}
