/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.Boolean#getValueBoolean <em>Value Boolean</em>}</li>
 * </ul>
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getBoolean()
 * @model
 * @generated
 */
public interface Boolean extends Primary, OutputExpression
{
  /**
   * Returns the value of the '<em><b>Value Boolean</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Boolean</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Boolean</em>' attribute.
   * @see #setValueBoolean(java.lang.Boolean)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getBoolean_ValueBoolean()
   * @model
   * @generated
   */
  java.lang.Boolean getValueBoolean();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.Boolean#getValueBoolean <em>Value Boolean</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Boolean</em>' attribute.
   * @see #getValueBoolean()
   * @generated
   */
  void setValueBoolean(java.lang.Boolean value);

} // Boolean
