/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;

import java.lang.String;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getBoolean <em>Boolean</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getBooleanObj <em>Boolean Obj</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getShort <em>Short</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getShortObj <em>Short Obj</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getInt <em>Int</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getIntObj <em>Int Obj</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getLong <em>Long</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getLongObj <em>Long Obj</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getFloat <em>Float</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getFloatObj <em>Float Obj</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getDouble <em>Double</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getDoubleObj <em>Double Obj</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getString <em>String</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DataType#getDefDataType <em>Def Data Type</em>}</li>
 * </ul>
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends EObject
{
  /**
   * Returns the value of the '<em><b>Boolean</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Boolean</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boolean</em>' attribute.
   * @see #setBoolean(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_Boolean()
   * @model
   * @generated
   */
  String getBoolean();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getBoolean <em>Boolean</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Boolean</em>' attribute.
   * @see #getBoolean()
   * @generated
   */
  void setBoolean(String value);

  /**
   * Returns the value of the '<em><b>Boolean Obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Boolean Obj</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boolean Obj</em>' attribute.
   * @see #setBooleanObj(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_BooleanObj()
   * @model
   * @generated
   */
  String getBooleanObj();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getBooleanObj <em>Boolean Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Boolean Obj</em>' attribute.
   * @see #getBooleanObj()
   * @generated
   */
  void setBooleanObj(String value);

  /**
   * Returns the value of the '<em><b>Short</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Short</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Short</em>' attribute.
   * @see #setShort(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_Short()
   * @model
   * @generated
   */
  String getShort();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getShort <em>Short</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Short</em>' attribute.
   * @see #getShort()
   * @generated
   */
  void setShort(String value);

  /**
   * Returns the value of the '<em><b>Short Obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Short Obj</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Short Obj</em>' attribute.
   * @see #setShortObj(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_ShortObj()
   * @model
   * @generated
   */
  String getShortObj();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getShortObj <em>Short Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Short Obj</em>' attribute.
   * @see #getShortObj()
   * @generated
   */
  void setShortObj(String value);

  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_Int()
   * @model
   * @generated
   */
  String getInt();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #getInt()
   * @generated
   */
  void setInt(String value);

  /**
   * Returns the value of the '<em><b>Int Obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int Obj</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Obj</em>' attribute.
   * @see #setIntObj(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_IntObj()
   * @model
   * @generated
   */
  String getIntObj();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getIntObj <em>Int Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int Obj</em>' attribute.
   * @see #getIntObj()
   * @generated
   */
  void setIntObj(String value);

  /**
   * Returns the value of the '<em><b>Long</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Long</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Long</em>' attribute.
   * @see #setLong(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_Long()
   * @model
   * @generated
   */
  String getLong();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getLong <em>Long</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Long</em>' attribute.
   * @see #getLong()
   * @generated
   */
  void setLong(String value);

  /**
   * Returns the value of the '<em><b>Long Obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Long Obj</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Long Obj</em>' attribute.
   * @see #setLongObj(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_LongObj()
   * @model
   * @generated
   */
  String getLongObj();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getLongObj <em>Long Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Long Obj</em>' attribute.
   * @see #getLongObj()
   * @generated
   */
  void setLongObj(String value);

  /**
   * Returns the value of the '<em><b>Float</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Float</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Float</em>' attribute.
   * @see #setFloat(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_Float()
   * @model
   * @generated
   */
  String getFloat();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getFloat <em>Float</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Float</em>' attribute.
   * @see #getFloat()
   * @generated
   */
  void setFloat(String value);

  /**
   * Returns the value of the '<em><b>Float Obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Float Obj</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Float Obj</em>' attribute.
   * @see #setFloatObj(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_FloatObj()
   * @model
   * @generated
   */
  String getFloatObj();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getFloatObj <em>Float Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Float Obj</em>' attribute.
   * @see #getFloatObj()
   * @generated
   */
  void setFloatObj(String value);

  /**
   * Returns the value of the '<em><b>Double</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Double</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Double</em>' attribute.
   * @see #setDouble(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_Double()
   * @model
   * @generated
   */
  String getDouble();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getDouble <em>Double</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Double</em>' attribute.
   * @see #getDouble()
   * @generated
   */
  void setDouble(String value);

  /**
   * Returns the value of the '<em><b>Double Obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Double Obj</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Double Obj</em>' attribute.
   * @see #setDoubleObj(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_DoubleObj()
   * @model
   * @generated
   */
  String getDoubleObj();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getDoubleObj <em>Double Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Double Obj</em>' attribute.
   * @see #getDoubleObj()
   * @generated
   */
  void setDoubleObj(String value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

  /**
   * Returns the value of the '<em><b>Def Data Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Def Data Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def Data Type</em>' reference.
   * @see #setDefDataType(DefDataType)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDataType_DefDataType()
   * @model
   * @generated
   */
  DefDataType getDefDataType();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DataType#getDefDataType <em>Def Data Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Def Data Type</em>' reference.
   * @see #getDefDataType()
   * @generated
   */
  void setDefDataType(DefDataType value);

} // DataType
