/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;

import java.lang.String;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Def Data Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DefDataValue#getName <em>Name</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DefDataValue#getDataTypeInstance <em>Data Type Instance</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DefDataValue#getValueDataValue <em>Value Data Value</em>}</li>
 * </ul>
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefDataValue()
 * @model
 * @generated
 */
public interface DefDataValue extends OutputExpression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefDataValue_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DefDataValue#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Data Type Instance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data Type Instance</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Type Instance</em>' containment reference.
   * @see #setDataTypeInstance(DataTypeInstance)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefDataValue_DataTypeInstance()
   * @model containment="true"
   * @generated
   */
  DataTypeInstance getDataTypeInstance();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DefDataValue#getDataTypeInstance <em>Data Type Instance</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Type Instance</em>' containment reference.
   * @see #getDataTypeInstance()
   * @generated
   */
  void setDataTypeInstance(DataTypeInstance value);

  /**
   * Returns the value of the '<em><b>Value Data Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Data Value</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Data Value</em>' reference.
   * @see #setValueDataValue(DefDataValue)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefDataValue_ValueDataValue()
   * @model
   * @generated
   */
  DefDataValue getValueDataValue();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DefDataValue#getValueDataValue <em>Value Data Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Data Value</em>' reference.
   * @see #getValueDataValue()
   * @generated
   */
  void setValueDataValue(DefDataValue value);

} // DefDataValue
