/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;

import java.lang.String;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Def Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DefFunction#getName <em>Name</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DefFunction#getInputParams <em>Input Params</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DefFunction#getOutputDataType <em>Output Data Type</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DefFunction#getFunctionBody <em>Function Body</em>}</li>
 * </ul>
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefFunction()
 * @model
 * @generated
 */
public interface DefFunction extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefFunction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DefFunction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Input Params</b></em>' containment reference list.
   * The list contents are of type {@link com.aestheticintegration.atto.itlDsl.InputParam}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Input Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Params</em>' containment reference list.
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefFunction_InputParams()
   * @model containment="true"
   * @generated
   */
  EList<InputParam> getInputParams();

  /**
   * Returns the value of the '<em><b>Output Data Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Output Data Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output Data Type</em>' containment reference.
   * @see #setOutputDataType(DataType)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefFunction_OutputDataType()
   * @model containment="true"
   * @generated
   */
  DataType getOutputDataType();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DefFunction#getOutputDataType <em>Output Data Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output Data Type</em>' containment reference.
   * @see #getOutputDataType()
   * @generated
   */
  void setOutputDataType(DataType value);

  /**
   * Returns the value of the '<em><b>Function Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Body</em>' containment reference.
   * @see #setFunctionBody(FunctionBody)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefFunction_FunctionBody()
   * @model containment="true"
   * @generated
   */
  FunctionBody getFunctionBody();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DefFunction#getFunctionBody <em>Function Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Body</em>' containment reference.
   * @see #getFunctionBody()
   * @generated
   */
  void setFunctionBody(FunctionBody value);

} // DefFunction
