/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;

import java.lang.String;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Def Test</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DefTest#getName <em>Name</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DefTest#getDefFunc <em>Def Func</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DefTest#getDataTypeValues <em>Data Type Values</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.DefTest#getOutputExpression <em>Output Expression</em>}</li>
 * </ul>
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefTest()
 * @model
 * @generated
 */
public interface DefTest extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefTest_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DefTest#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Def Func</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Def Func</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def Func</em>' reference.
   * @see #setDefFunc(DefFunction)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefTest_DefFunc()
   * @model
   * @generated
   */
  DefFunction getDefFunc();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DefTest#getDefFunc <em>Def Func</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Def Func</em>' reference.
   * @see #getDefFunc()
   * @generated
   */
  void setDefFunc(DefFunction value);

  /**
   * Returns the value of the '<em><b>Data Type Values</b></em>' containment reference list.
   * The list contents are of type {@link com.aestheticintegration.atto.itlDsl.DataTypeValue}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data Type Values</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Type Values</em>' containment reference list.
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefTest_DataTypeValues()
   * @model containment="true"
   * @generated
   */
  EList<DataTypeValue> getDataTypeValues();

  /**
   * Returns the value of the '<em><b>Output Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Output Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output Expression</em>' containment reference.
   * @see #setOutputExpression(OutputExpression)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getDefTest_OutputExpression()
   * @model containment="true"
   * @generated
   */
  OutputExpression getOutputExpression();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.DefTest#getOutputExpression <em>Output Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output Expression</em>' containment reference.
   * @see #getOutputExpression()
   * @generated
   */
  void setOutputExpression(OutputExpression value);

} // DefTest
