/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;

import java.lang.String;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exception</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.Exception#getValueException <em>Value Exception</em>}</li>
 * </ul>
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getException()
 * @model
 * @generated
 */
public interface Exception extends OutputExpression
{
  /**
   * Returns the value of the '<em><b>Value Exception</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Exception</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Exception</em>' attribute.
   * @see #setValueException(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getException_ValueException()
   * @model
   * @generated
   */
  String getValueException();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.Exception#getValueException <em>Value Exception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Exception</em>' attribute.
   * @see #getValueException()
   * @generated
   */
  void setValueException(String value);

} // Exception
