/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp Or If Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.ExpOrIfStatement#getOutputExpression <em>Output Expression</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.ExpOrIfStatement#getIfStatement <em>If Statement</em>}</li>
 * </ul>
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getExpOrIfStatement()
 * @model
 * @generated
 */
public interface ExpOrIfStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Output Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Output Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output Expression</em>' containment reference.
   * @see #setOutputExpression(OutputExpression)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getExpOrIfStatement_OutputExpression()
   * @model containment="true"
   * @generated
   */
  OutputExpression getOutputExpression();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.ExpOrIfStatement#getOutputExpression <em>Output Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output Expression</em>' containment reference.
   * @see #getOutputExpression()
   * @generated
   */
  void setOutputExpression(OutputExpression value);

  /**
   * Returns the value of the '<em><b>If Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>If Statement</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>If Statement</em>' containment reference.
   * @see #setIfStatement(IfStatement)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getExpOrIfStatement_IfStatement()
   * @model containment="true"
   * @generated
   */
  IfStatement getIfStatement();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.ExpOrIfStatement#getIfStatement <em>If Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If Statement</em>' containment reference.
   * @see #getIfStatement()
   * @generated
   */
  void setIfStatement(IfStatement value);

} // ExpOrIfStatement
