/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Float</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.Float#getValueFloat <em>Value Float</em>}</li>
 * </ul>
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getFloat()
 * @model
 * @generated
 */
public interface Float extends Primary, OutputExpression
{
  /**
   * Returns the value of the '<em><b>Value Float</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Float</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Float</em>' attribute.
   * @see #setValueFloat(java.lang.Float)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getFloat_ValueFloat()
   * @model
   * @generated
   */
  java.lang.Float getValueFloat();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.Float#getValueFloat <em>Value Float</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Float</em>' attribute.
   * @see #getValueFloat()
   * @generated
   */
  void setValueFloat(java.lang.Float value);

} // Float
