/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;

import java.lang.String;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Param</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.InputParam#getName <em>Name</em>}</li>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.InputParam#getInputDataType <em>Input Data Type</em>}</li>
 * </ul>
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getInputParam()
 * @model
 * @generated
 */
public interface InputParam extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getInputParam_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.InputParam#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Input Data Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Input Data Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Data Type</em>' containment reference.
   * @see #setInputDataType(DataType)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getInputParam_InputDataType()
   * @model containment="true"
   * @generated
   */
  DataType getInputDataType();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.InputParam#getInputDataType <em>Input Data Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input Data Type</em>' containment reference.
   * @see #getInputDataType()
   * @generated
   */
  void setInputDataType(DataType value);

} // InputParam
