/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.Integer#getValueInteger <em>Value Integer</em>}</li>
 * </ul>
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getInteger()
 * @model
 * @generated
 */
public interface Integer extends Primary, OutputExpression
{
  /**
   * Returns the value of the '<em><b>Value Integer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Integer</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Integer</em>' attribute.
   * @see #setValueInteger(java.lang.Integer)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getInteger_ValueInteger()
   * @model
   * @generated
   */
  java.lang.Integer getValueInteger();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.Integer#getValueInteger <em>Value Integer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Integer</em>' attribute.
   * @see #getValueInteger()
   * @generated
   */
  void setValueInteger(java.lang.Integer value);

} // Integer
