/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;

import java.lang.String;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Null</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.Null#getValueNull <em>Value Null</em>}</li>
 * </ul>
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getNull()
 * @model
 * @generated
 */
public interface Null extends Primary, OutputExpression
{
  /**
   * Returns the value of the '<em><b>Value Null</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Null</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Null</em>' attribute.
   * @see #setValueNull(String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getNull_ValueNull()
   * @model
   * @generated
   */
  String getValueNull();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.Null#getValueNull <em>Value Null</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Null</em>' attribute.
   * @see #getValueNull()
   * @generated
   */
  void setValueNull(String value);

} // Null
