/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getPrimary()
 * @model
 * @generated
 */
public interface Primary extends EObject
{
} // Primary
