/**
 * generated by Xtext 2.12.0
 */
package com.aestheticintegration.atto.itlDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aestheticintegration.atto.itlDsl.String#getValueString <em>Value String</em>}</li>
 * </ul>
 *
 * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getString()
 * @model
 * @generated
 */
public interface String extends Primary, OutputExpression
{
  /**
   * Returns the value of the '<em><b>Value String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value String</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value String</em>' attribute.
   * @see #setValueString(java.lang.String)
   * @see com.aestheticintegration.atto.itlDsl.ItlDslPackage#getString_ValueString()
   * @model
   * @generated
   */
  java.lang.String getValueString();

  /**
   * Sets the value of the '{@link com.aestheticintegration.atto.itlDsl.String#getValueString <em>Value String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value String</em>' attribute.
   * @see #getValueString()
   * @generated
   */
  void setValueString(java.lang.String value);

} // String
